version: '3.7'

services:
  ghost:
    image: ghost
    restart: unless-stopped
    ports:
      - ${GHOST_PORT}:2368
    depends_on: 
      - ghost-db
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__database: ${MYSQL_DATABASE}
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      NODE_ENV: development
      url: ${GHOST_URL}
    volumes: 
      - ./ghost/content:/var/lib/ghost/content

  ghost-db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ghost-db:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    depends_on: 
      - ghost-db

volumes:
  ghost-db: